name: vigie
description: Gérer un serveur Linux depuis une seule interface terminal (utilisateurs, processus, services).
version: 0.6.1
repository: https://github.com/nuageeee/vigie

environment:
  sdk: ^3.13.5

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  commander_ui: ^3.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  hotreloader: ^4.4.0
